# Generated by Django 4.1.6 on 2023-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_aluno_data_nascimento_alter_curso_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
