# Generated by Django 4.1.6 on 2023-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_aluno_id_remove_curso_id_alter_aluno_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(help_text='%Y-%m-%d'),
        ),
    ]
